from fpdf import FPDF
import os, glob

def CreatePDF(data, text):
    class PDF(FPDF):
        def header(self):
            self.set_draw_color(37, 99, 235)
            self.set_line_width(1)
            self.rect(5, 5, 200, 287)

            self.set_font('Arial', 'B', 10)
            self.set_text_color(150, 150, 150)
            self.cell(0, 10, 'Generated by Expedition AI', 0, 1, 'R')
            self.ln(5)
        
        def footer(self):
            self.set_y(-15)
            self.set_font('Arial', 'I', 8)
            self.set_text_color(128)
            self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    pdf = FPDF()
    pdf.add_page()
    
    def safe_text(text):
        return text.encode('latin-1', 'ignore').decode('latin-1')

    # ---- TITLE ----
    pdf.set_font("Arial", "B", 24)
    pdf.set_text_color(37, 99, 235)
    pdf.cell(0, 10, safe_text(f"Expedition to {data['location']}"), ln=True, align='C')

    pdf.set_font("Arial", "", 12)
    pdf.set_text_color(50, 50, 50)
    subtitle = f"{data['startDate']} to {data['endDate']}  |  {data['occasion']}  |  Budget: ${data['budget']}"
    pdf.cell(0, 10, safe_text(subtitle), ln=True, align='C')

    pdf.set_draw_color(200, 200, 200)
    pdf.set_line_width(0.5)
    pdf.line(20, 45, 190, 45)
    pdf.ln(15)

    # ---- BODY ----
    pdf.set_font("Arial", "B", 16)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Travel Schedule", ln=True)

    pdf.set_font("Arial", size=11)
    pdf.set_text_color(30, 30, 30)

    clean_text = text.replace('**', '').replace('##', '').replace('* ', '  • ')
    pdf.multi_cell(0, 7, safe_text(clean_text))

    # ---- OUTPUT ----
    save_dir = os.path.join(os.getcwd(), '_pdfcache')
    os.makedirs(save_dir, exist_ok=True)
    filename = f"{data['location']}_Trip_Plan.pdf".replace(" ", "_").replace("/", "-")
    filepath = os.path.join(save_dir, filename)
    pdf.output(filepath)
    return filepath

def CleanCache(logger):
    cache_dir = os.path.join(os.getcwd(), '_pdfcache')
    if os.path.exists(cache_dir):
        files = glob.glob(os.path.join(cache_dir, "*"))
        for f in files:
            try:
                os.remove(f)
            except Exception as e:
                logger.error(f"Error deleting old file {f}: {e}")
